### PR TITLE
add UMD to allow module exporting

### PR DESCRIPTION
**Pull request by tedwardmah**
Hi CrossLead team! Thank you for making this package available!  My name is Ted, I came across your package while trying to find a way to incorporate the Zendesk embeddable into our company's application in a sane, testable way (easier said than done).  

We use npm + browserify for our dependency management, however, so if we wanted to use angular-zendesk-widget as-is we would need to add some sort of debowerify step in our build, which I'd rather avoid.

Did you have any existing plans to offer this package via npm as well?  If not, I believe that with a couple more commands to actually publish, this PR would enable you to offer NPM support by adding a UMD definition to the concat step of your build.  (https://github.com/umdjs/umd).  

I'm not sure what your procedures are for accepting PRs, so I welcome feedback and am happy to work with you to make sure I've adhered to your requirements.

And again, thanks for making this!

### CODE REVIEW

**Comment by yangchristian** [comment]
Thanks @tedwardmah! Although we haven't used UMD patterns, your changes look good from a quick glance. Most likely it'll take until the weekend before I'll have time to review more closely, merge, and publish new versions (both on `npm` and `bower`).

**Comment by tedwardmah** [comment]
@yangchristian thanks for the quick reply, take your time and let me know what you think

**Comment by yangchristian** [comment]
@tedwardmah: Just published `v0.1.3` to both `npm` and `bower`. Thanks again!

**Comment by tedwardmah** [comment]
hey @yangchristian thanks again for your quick work on this.  I wasn't able to work on integrating until this week, but I finally got to close out the ticket and happy to report that I'm pointing to the version on NPM currently.  Thanks!

**Pull request merged**
